blank_issues_enabled: false
contact_links:
  - name: ๐ฌ GitHub Discussions
    url: https://github.com/hnlaptopstore/hn-laptop-store/discussions
    about: ุงุณุฃู ุฃุณุฆูุฉ ุนุงูุฉ ุฃู ูุงูุด ุงูุฃููุงุฑ ูุน ุงููุฌุชูุน
  - name: ๐ง ุงูุจุฑูุฏ ุงูุฅููุชุฑููู
    url: mailto:support@hnlaptopstore.com
    about: ุงุชุตู ุจูุง ูุจุงุดุฑุฉ ููุญุตูู ุนูู ุงูุฏุนู
  - name: ๐ ูุดููุฉ ุฃูููุฉ
    url: mailto:security@hnlaptopstore.com
    about: ุฃุจูุบ ุนู ุซุบุฑุฉ ุฃูููุฉ ุจุทุฑููุฉ ูุณุคููุฉ
  - name: ๐ ุงููุซุงุฆู
    url: https://docs.hnlaptopstore.com
    about: ุงูุฑุฃ ุงููุซุงุฆู ุงูุฑุณููุฉ
  - name: ๐ ุงููููุน ุงูุฑุณูู
    url: https://hnlaptopstore.com
    about: ุฒุฑ ูููุนูุง ุงูุฑุณูู